version: "3.7"

services:
    environment:
        - COMPOSE_CONVERT_WINDOWS_PATHS=1

    python_backend:
        build: ./backend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/usr/src/app

    node_frontend:
        build: ./frontend          
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/app            
        environment:
            - CHOKIDAR_USEPOLLING=true

