version: "3.7"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - COMPOSE_CONVERT_WINDOWS_PATHS=1

