version: "3.7"

services:
    python_backend:
        build: ./backend
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app
     
    node_frontend:
        build: ./frontend          
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/src/app            
        environment:
            - CHOKIDAR_USEPOLLING=true


