version: "3.7"

services:
  backend_python:
    build:
      context: ./backend

  frontend_node:
    build:
      context: ./frontend
    stdin_open: true
    depends_on:
      - "backend_python"
    ports:
      - "3000:3000"