version: '3.8'
services:
  node:
    image: "node:16-slim"
    user: "node"
    working_dir: /usr/src/app
    volumes:
      - ./:/home/node/app
    expose:
      - "3000:3000"
    command: "npm start"
