version: "3.8"

services:
    python_backend:
        build: ./backend
        ports:
            - 8000:8000
     
    node_frontend:
        build: ./frontend                 
        ports:
            - 3000:3000          
        environment:
            - CHOKIDAR_USEPOLLING=true


